### ISSUE TITLE
Battle-tested vesting contract research

### ISSUE THREAD

**Issue by Luke-Rogerson** [exciteddao/excited-contracts#9]
Some ones to look at:

- [x] RibbonFinance (Luke)
- [x] Opyn (Shahar)
- [ ] Hegic (Luke)
- [x] GMX (Shahar)

**Comment by shaharyakir** [comment]
Opyn: 

https://medium.com/opyn/introducing-opyn-developer-toolkit-2bfd5bcc7a92

https://gist.github.com/alexisgauba/cf055f521bcfded018116f3f37074f67, which leads to:
https://github.com/banteg/yearn-vesting-escrow/blob/master/contracts/VestingEscrowSimple.vy#L94, where vesting actually happens.

**Comment by shaharyakir** [comment]
Gmx: https://github.com/gmx-io/gmx-contracts/blob/3b941172f1d00a794183f371218c0f83635e90ff/contracts/staking/Vester.sol#L349

**Comment by Luke-Rogerson** [comment]
Could not find Hegic vesting implementation
